#!/bin/sh
# Carnice wrapper script template
# Auto-generated by carnice-local-llm skill
# Customize MODEL path, THREADS, PORT, and LOGDIR as needed

# === Configuration ===
SERVER_BIN="${LLAMA_SERVER:-$HOME/llama.cpp/build/bin/llama-server}"
MODEL="${CARNICE_MODEL:-$HOME/llama-models/carnice-9b-q4_k_m.gguf}"
HOST="127.0.0.1"
PORT="${CARNICE_PORT:-8080}"
THREADS="${CARNICE_THREADS:-8}"
LOGDIR="${CARNICE_LOGDIR:-$HOME/.local/share/carnice}"
LOGFILE="$LOGDIR/llama-server.log"

# === Don't edit below unless you know what you're doing ===

mkdir -p "$LOGDIR"

# Kill any existing server on the same port
pkill -f "llama-server.*${PORT}" 2>/dev/null
sleep 1

# Start llama-server in background, logging to file
$SERVER_BIN \
    -m "$MODEL" \
    --host "$HOST" \
    --port "$PORT" \
    -t "$THREADS" \
    --reasoning off \
    >> "$LOGFILE" 2>&1 &

LLAMA_PID=$!

# Run hermes with carnice profile
hermes -p carnice "$@"
HERMES_EXIT=$?

# Kill server when hermes exits
kill $LLAMA_PID 2>/dev/null

exit $HERMES_EXIT
